# 🔐 GitLab CI/CD - Ritech Fechaduras
stages:
  - deploy
  - invalidate

variables:
  S3_BUCKET: "ritech-fechaduras-site"
  CLOUDFRONT_DISTRIBUTION_ID: "E2DXHLX2VFCW6L"

deploy_s3:
  stage: deploy
  image: amazon/aws-cli:latest
  script:
    - aws s3 sync . s3://$S3_BUCKET --exclude "*.md" --exclude ".git/*" --exclude "backups/*" --delete
  only:
    - main

invalidate_cache:
  stage: invalidate
  image: amazon/aws-cli:latest
  script:
    - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
  only:
    - main